name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 如果你的主分支是 master，请改为 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 允许工作流写入仓库内容

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 使用你项目所需的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --base=/site-issue/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Vue 项目默认构建目录
          keep_files: false    # 部署前清除 gh-pages 分支原有内容
